### ISSUE TITLE
Getting unhandled exception

### ISSUE THREAD

**Issue by KidkArolis** [QubitProducts/qubit-cli#349]
```
$ qubit login
✓    Setting up Qubit-CLI, this may take a few mins
✓    We'll now generate a TSL certificate and install it into your OS as a trusted certificate
✓    This is to make sure that browsers don't block Qubit-CLI from serving to https sites
✓    You will be asked for your sudo password
✓    If you'd like to inspect/remove the installed certificate, you can find it in your keychain
✓    All done!
✓    The certificate has been created in /Users/karolis/.qubit-ssland has been added to your system as a trusted certificate.
✓    Please log in...
✓    Opening login url: https://qubit.auth0.com/authorize?response_type=code&scope=openid%20profile%20offline_access&client_id=BlkYEHauoKWvGcN2my1TGlqh5dHHuW30&redirect_uri=https%3A%2F%2Flocalhost%3A41337%2Fcallback&code_challenge=hwABe93zXhE-LLjwPdbu_O2FUX4nKp4HlRwaa1Lw1uo&code_challenge_method=S256
(node:8907) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/Users/karolis/qubit/smartserve/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/karolis/qubit/smartserve/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/karolis/qubit/smartserve/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8907) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8907) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by samuelfullerthomas** [comment]
Hey @KidkArolis, thanks for filling an issue! Do you have the version number you on when you saw this error?

**Comment by KidkArolis** [comment]
I'm afraid I don't. But it would probably be the last version released before 7 days ago. You can't reproduce the issue?
