### ISSUE TITLE
Unable to run after update to 1.77.2

### ISSUE THREAD

**Issue by bRRRITSCOLD** [QubitProducts/qubit-cli#456]
**_Specs_**
_OS_: macOS Big Sur 11.3.1 (20E241)
_CPU_: 2.6 GHz 6-Core Intel Core i7
_Memory_: 16 GB 2667 MHz DDR4
_Graphics_: AMD Radeon Pro 5300M 4 GB  -  Intel UHD Graphics 630 1536 MB
_Node Version_: 16.7.0
_qubit-cli version_: 1.77.2 (latest)

Everything worked up until about 5:20 PM last night (EST) when we went to push experiences and we were prompted to update. Now our whole team receives something like the below when running any command `qubit`, `qubit push`, `qubit login`, `qubit pull`, etc. So, not even local development can take place currently. Major blocker.

``` bash
$ qubit login

✓    Qubit-CLI needs to complete its installation, this may take a minute
✓    Installing additional dependencies...
cp: public-package.json: Permission denied
make: *** [install-private-packages] Error 1

/xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/node_modules/execa/index.js:236
                                err = new Error(`Command failed: ${joinedCmd}${output}`);
                                      ^

Error: Command failed: make install-private-packages
    at /xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/node_modules/execa/index.js:236:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installQubitDeps (/xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/src/lib/install-qubit-deps.js:25:5)
    at async run (/xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/src/cmd/index.js:10:29) {
  code: 2,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'make install-private-packages',
  timedOut: false
}



$ sudo qubit login

✓    Qubit-CLI needs to complete its installation, this may take a minute
✓    Installing additional dependencies...
cp: package-lock.json: No such file or directory
make: *** [install-private-packages] Error 1

/xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/node_modules/execa/index.js:236
                                err = new Error(`Command failed: ${joinedCmd}${output}`);
                                      ^

Error: Command failed: make install-private-packages
    at /xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/node_modules/execa/index.js:236:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installQubitDeps (/xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/src/lib/install-qubit-deps.js:25:5)
    at async run (/xxxxx/xxxxx/.nvm/versions/node/v16.7.0/lib/node_modules/qubit-cli/src/cmd/index.js:10:29) {
  code: 2,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'make install-private-packages',
  timedOut: false
}
```

I have done the following in trying to fix this

1. `npm uninstall -g qubit-cli`
2. `npm clean cache --force`
3. `npm install -g qubit-cli`

and unfortunately none of it works.

When reinstalling version `1.77.1` local development and usage of the cli works fine, but due to the tool pushes to experiences aren't allowed unless you are using the most current cli version. And the vicious cycle begins :) Please let me know what other info you may need! Thank you all!

**Comment by bRRRITSCOLD** [comment]
got an update to give a try now, they’ve released an update that rolls back a few recent changes. it seems to have worked for now.
